# Aliases
fold: TS_5_4
ratios: null
vxs: 10
num_classes: 7
lr: 0.1
momentum: 0.5
nesterov: true
weight_decay: 0
t0: 50
tmult: 1
batch_size: 2
num_workers: 2
persistent_workers: true
prefetch_factor: 2
every_n_epochs: "${eval: 1 if not ${callbacks.checkpoint.every_n_train_steps} and not ${callbacks.checkpoint.train_time_interval} else None}"
freeze_encoder: true
eta_min: 1e-3
warmup: 100
gradient_clip_val: 10
precision: "bf16-true"
accelerator: "tpu"
strategy: auto
fast_dev_run: false
max_epochs: 1000
val_check_interval: null
profiler_name: torch
ckpt_path: null
repeat: [1, 1]

# Data Management
copick:
  base:
    voxel_spacing: "${vxs}"
    resolution: "0"
    tomotype: denoised
  fit:
    mode: fit
    path: /kaggle/working/kaggle_project_czii/src/cryoetpicker/config/copick_fit.json
    fold: "${fold}"
    user_id: copick
    session_id: "0"
    repeat: "${repeat}"
  test:
    mode: test
    path: /kaggle/working/kaggle_project_czii/src/cryoetpicker/config/copick_test.json
    repeat: [8, ]

#Caching
cache_ds:
  train: true
  eval: true

# Data Transforms
transforms:
  base:
    roi_size: [96, 96, 96]
  train:
    mode: train
    keys: ["input", "target"]
    num_samples: 4
    num_classes: "${num_classes}" # BG included
    ratios: "${ratios}"
  validation:
    mode: validation
    keys: ["input", "target"]
  test:
    mode: test
    keys: ["input"]

# DataLoaders
loader:
  train:
    batch_size: "${batch_size}"
    num_workers: "${num_workers}"
    shuffle: true
    drop_last: true
    persistent_workers: "${persistent_workers}"
    prefetch_factor: "${prefetch_factor}"
    pin_memory: false
  eval:
    batch_size: 1
    num_workers: 2
    shuffle: false
    drop_last: true
    persistent_workers: false
    prefetch_factor: 2
    pin_memory: false

# Metrics
metrics:
  score:
    super:
      compute_on_cpu: true
      dist_sync_on_step: false
      dist_sync_fn: null
      distributed_available_fn: null
      sync_on_compute: true
      compute_with_cache: true
    init:
      beta: 4.0
      multiplier: 1.5
      voxel_spacing: "${copick.base.voxel_spacing}"

# Post-Processing
pp:
  nms_radius: 16
  num_classes: "${transforms.train.num_classes}"
  topk: 1000
  roi_size: "${transforms.base.roi_size}"
  tomo_size: [184, 630, 630]
  interpolation: "nearest-exact"
  align_corners: null

# Callbacks
callbacks:
  checkpoint:
    filename: "{epoch}-{step}-{train_loss:.2e}-{val_loss:.2e}-{score:.2e}"
    monitor: train_loss
    verbose: false
    save_last: true
    save_top_k: 3
    mode: min
    auto_insert_metric_name: true
    save_weights_only: false
    every_n_train_steps: 0  # x to deactivate
    train_time_interval: null
    every_n_epochs: "${every_n_epochs}"
    save_on_train_epoch_end: false
    enable_version_counter: false
  lr_monitor:
    logging_interval: step
    log_momentum: true
    log_weight_decay: true

# Model
models:
  flexible:
    spatial_dims: 3
    in_channels: 1
    out_channels: "${transforms.train.num_classes}" # 2 classes: background and motor
    backbone: resnet34
    pretrained: true
    upsample: "deconv"
    decoder_channels: [256, 128, 64, 32]
    skip_connect: 4

# reproductibility
determinism:
  seed: 4294967295
  cudnn_backend: false
  use_deterministic_algorithms: false
  warn_only: true

# Training
training:
  supervision:
    freeze_encoder: "${freeze_encoder}"
    deep_contributions: [1, 1, 1] # reverse indexed depth => output should be last [avg_deloss, max_loss, dice_loss]
    weighted: false
  augs:
    mixup:
      add: false
      beta: 5.0
      p: 0.0
    cutmix:
      beta: 5.0
      dims: [-2, -1]
      p: 0.0
    smoothing: 0.0
  sub_batch:
    train: -1
    eval: 4
  ckpt_path: "${ckpt_path}"

# Optimizers
optimizer:
  name: SGD
  sgd:
    lr: "${lr}"
    momentum: "${momentum}"
    nesterov: "${nesterov}"
    weight_decay: "${weight_decay}"
  adam:
    lr: "${lr}"
    weight_decay: "${weight_decay}"
  adamw:
    lr: "${lr}"
    weight_decay: "${weight_decay}"
  adamw_plus:
    lr: "${lr}"
    weight_decay: "${weight_decay}"

# Optmization
deep_loss:
    include_background: true
    to_onehot_y: true
    gamma: 2.
    alpha: null
    weight: [216, 14e3, 11.2e4]
    reduction: mean
    use_softmax: true
    num_classes: "${transforms.train.num_classes}"
    lambda_max: 0.25
    lambda_avg: 0.25
    weighted: true
    depth: 3
    max_pool:
      kernel_size: 4
      stride: 4
      padding: 0
      dilation: 1
    avg_pool:
      kernel_size: 4
      stride: 4
      padding: 0

dice:
  include_background: true
  to_onehot_y: true
  sigmoid: false
  softmax: true
  other_act: null
  squared_pred: false
  jaccard: false
  reduction: none
  smooth_nr: 1e-10
  smooth_dr: 1e-10
  batch: false
  weight: null

w_init:
  dist: normal
  a: 0.1
  mode: fan_out
  nonlinearity: leaky_relu

# Profiler
profiler:
  accelerator: "${profiler_name}"
  xla:
    port: 9001
  torch:
    emit_nvtx: true
    prof_filename: prof_filename.txt

# Scheduler
scheduler:
  name: cosine_wr
  warmup: "${warmup}"
  restart_scheduler: true
  multistep:
    milestones: 2
    gamma: "${eta_min}"
  cosine:
    T_max: 100
    eta_min: "${eta_min}"
    last_epoch: -1
  cosine_wr:
    T_0: "${t0}"
    T_mult: "${tmult}"
    eta_min: "${eta_min}"
    last_epoch: -1
  linear:
    start_factor: "${eta_min}"
    end_factor: 1.0
    total_iters: "${warmup}"

# Trainer
trainers:
  callable:
    logger: "${eval: not ${trainers.lightning.barebones} and not ${trainers.lightning.fast_dev_run}}"
    callbacks: "${eval: True if not ${trainers.lightning.barebones} and not ${trainers.lightning.fast_dev_run} else None}"
    profiler: "${eval: None if not ${trainers.lightning.barebones} and not ${trainers.lightning.fast_dev_run} else None}"
  lightning:
    accumulate_grad_batches: 1
    gradient_clip_algorithm: norm
    gradient_clip_val: "${gradient_clip_val}"
    precision: "${precision}"
    sync_batchnorm: true
    accelerator: "${accelerator}"
    devices: auto
    num_nodes: 1
    strategy: "${strategy}"
    use_distributed_sampler: true
    reload_dataloaders_every_n_epochs: 0
    benchmark: null
    barebones: false
    detect_anomaly: false
    fast_dev_run: "${fast_dev_run}"
    num_sanity_val_steps: 0
    overfit_batches: 0
    plugins: null
    default_root_dir: "${save_dir}"
    enable_checkpointing: true
    enable_model_summary: false
    enable_progress_bar: true
    log_every_n_steps: 2
    model_registry: null
    check_val_every_n_epoch: "${eval: 1 if not ${trainers.lightning.val_check_interval} else None}"
    inference_mode: true
    limit_predict_batches: 1.0
    limit_test_batches: 1.0
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    max_epochs: "${max_epochs}"
    min_epochs: null
    max_steps: -1
    max_time: null
    min_steps: null
    val_check_interval: "${val_check_interval}"
    deterministic: "warn"

save_dir: "/kaggle/working"
